// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0XQJLy7qhKqhlStNpdd5Tuwvi887Fkng',
    appId: '1:643332160518:web:71a70bb823325a24be1787',
    messagingSenderId: '643332160518',
    projectId: 'my-guard-8a24f',
    authDomain: 'my-guard-8a24f.firebaseapp.com',
    storageBucket: 'my-guard-8a24f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UQtmBWUGPS9p8Iwk3V3LpjJelZeUkJc',
    appId: '1:643332160518:android:4629e438deefbe28be1787',
    messagingSenderId: '643332160518',
    projectId: 'my-guard-8a24f',
    storageBucket: 'my-guard-8a24f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqYnpxdL48-kZI3zjHQcva6b1JHKqtNM',
    appId: '1:643332160518:ios:5df0c2086949f2fdbe1787',
    messagingSenderId: '643332160518',
    projectId: 'my-guard-8a24f',
    storageBucket: 'my-guard-8a24f.appspot.com',
    iosClientId: '643332160518-5dkse85i0q94qj6i24vnl177df17h8u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGuard',
  );
}
